import { ColorConfig } from './types';

export const CARD_VERSION = '1.6.0';

/** Geometry of the tank inside the 200x300 SVG viewBox. */
export const TANK = {
  x: 50,
  y: 50,
  width: 100,
  height: 200,
  radius: 12,
} as const;

/** Specific heat capacity of water in kJ/(kg·K). */
export const WATER_HEAT_CAPACITY = 4.186;

export const DEFAULT_COLORS: Required<ColorConfig> = {
  boiler_fill: '#4CAF50',
  boiler_stroke: '#546E7A',
  cold_water: '#2196F3',
  warm_water: '#FF9800',
  hot_water: '#F44336',
  gradient_start: '#2196F3',
  gradient_end: '#F44336',
};

// Theme color presets
export const THEMES: Record<string, ColorConfig> = {
  ocean: {
    boiler_fill: '#4DD0E1',
    boiler_stroke: '#0097A7',
    cold_water: '#B3E5FC',
    warm_water: '#4FC3F7',
    hot_water: '#0288D1',
    gradient_start: '#E1F5FE',
    gradient_end: '#01579B',
  },
  sunset: {
    boiler_fill: '#FF9800',
    boiler_stroke: '#E65100',
    cold_water: '#FFE0B2',
    warm_water: '#FFB74D',
    hot_water: '#E64A19',
    gradient_start: '#FFF3E0',
    gradient_end: '#BF360C',
  },
  forest: {
    boiler_fill: '#66BB6A',
    boiler_stroke: '#2E7D32',
    cold_water: '#C8E6C9',
    warm_water: '#81C784',
    hot_water: '#43A047',
    gradient_start: '#E8F5E9',
    gradient_end: '#1B5E20',
  },
  fire: {
    boiler_fill: '#FF5722',
    boiler_stroke: '#BF360C',
    cold_water: '#FFCCBC',
    warm_water: '#FF7043',
    hot_water: '#D84315',
    gradient_start: '#FBE9E7',
    gradient_end: '#4E342E',
  },
  ice: {
    boiler_fill: '#81D4FA',
    boiler_stroke: '#0277BD',
    cold_water: '#E1F5FE',
    warm_water: '#4FC3F7',
    hot_water: '#0288D1',
    gradient_start: '#F1F8FB',
    gradient_end: '#01579B',
  },
};

// Localization strings
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  cs: {
    average_temp: 'Průměrná teplota',
    heating: 'Topí se',
    target: 'Cílová teplota',
    anode_check: 'Kontrola anody',
    cleaning_check: 'Čištění',
    days_remaining: 'zbývá dní',
    overdue: 'po termínu',
    power_consumption: 'Spotřeba',
    heating_source: 'Zdroj ohřevu',
    low_temperature: 'Nízká teplota!',
    temperature_drop: 'Prudký pokles teploty!',
    legionella_risk: 'Riziko legionely - ohřejte na 60°C',
    unusual_consumption: 'Neobvyklá spotřeba energie',
    maintenance_due: 'Údržba je potřeba',
    turn_on: 'Zapnout',
    turn_off: 'Vypnout',
    control: 'Ovládání',
    // v1.6.0
    maintenance: 'Údržba',
    anode: 'Anoda',
    cleaning: 'Čištění',
    not_set: 'Nenastaveno',
    no_sensors: 'Nejsou nakonfigurovány žádné senzory',
    remaining_days: 'Zbývá {days} dní',
    overdue_days: 'Po termínu ({days} dní)',
    status_heating: 'Ohřev',
    status_ready: 'Připraveno',
    status_cooling: 'Chladne',
    hot_water: 'Teplá voda',
    showers: 'sprch',
    stored_energy: 'Uložená energie',
    heat_loss: 'Tepelná ztráta',
    time_to_cold: 'Vystydne za',
    energy_today: 'Dnes',
    history: 'Historie teplot',
    show_history: 'Zobrazit historii',
    hide_history: 'Skrýt historii',
    no_history: 'Zatím nejsou nasbíraná data',
    operation_mode: 'Režim',
    target_control: 'Cílová teplota',
    electric_heating: 'Elektrický ohřev',
    solar_heating: 'Solární ohřev',
    gas_heating: 'Plynový ohřev',
    heat_pump_heating: 'Tepelné čerpadlo',
    mode_eco: 'Eko',
    mode_performance: 'Výkon',
    mode_high_demand: 'Vysoká spotřeba',
    mode_heat_pump: 'Tep. čerpadlo',
    mode_electric: 'Elektřina',
    mode_gas: 'Plyn',
    mode_off: 'Vypnuto',
    unavailable_entity: 'Entita nenalezena',
  },
  en: {
    average_temp: 'Average Temperature',
    heating: 'Heating',
    target: 'Target Temperature',
    anode_check: 'Anode Check',
    cleaning_check: 'Cleaning',
    days_remaining: 'days remaining',
    overdue: 'overdue',
    power_consumption: 'Consumption',
    heating_source: 'Heating Source',
    low_temperature: 'Low temperature!',
    temperature_drop: 'Rapid temperature drop!',
    legionella_risk: 'Legionella risk - heat to 60°C',
    unusual_consumption: 'Unusual energy consumption',
    maintenance_due: 'Maintenance required',
    turn_on: 'Turn On',
    turn_off: 'Turn Off',
    control: 'Control',
    // v1.6.0
    maintenance: 'Maintenance',
    anode: 'Anode',
    cleaning: 'Cleaning',
    not_set: 'Not set',
    no_sensors: 'No sensors configured',
    remaining_days: '{days} days left',
    overdue_days: 'Overdue ({days} days)',
    status_heating: 'Heating',
    status_ready: 'Ready',
    status_cooling: 'Cooling down',
    hot_water: 'Hot water',
    showers: 'showers',
    stored_energy: 'Stored energy',
    heat_loss: 'Heat loss',
    time_to_cold: 'Cold in',
    energy_today: 'Today',
    history: 'Temperature history',
    show_history: 'Show history',
    hide_history: 'Hide history',
    no_history: 'No data collected yet',
    operation_mode: 'Mode',
    target_control: 'Target temperature',
    electric_heating: 'Electric heating',
    solar_heating: 'Solar heating',
    gas_heating: 'Gas heating',
    heat_pump_heating: 'Heat pump',
    mode_eco: 'Eco',
    mode_performance: 'Performance',
    mode_high_demand: 'High demand',
    mode_heat_pump: 'Heat pump',
    mode_electric: 'Electric',
    mode_gas: 'Gas',
    mode_off: 'Off',
    unavailable_entity: 'Entity not found',
  },
  de: {
    average_temp: 'Durchschnittstemperatur',
    heating: 'Heizung',
    target: 'Zieltemperatur',
    anode_check: 'Anode Prüfung',
    cleaning_check: 'Reinigung',
    days_remaining: 'Tage übrig',
    overdue: 'überfällig',
    power_consumption: 'Verbrauch',
    heating_source: 'Heizquelle',
    low_temperature: 'Niedrige Temperatur!',
    temperature_drop: 'Schneller Temperaturabfall!',
    legionella_risk: 'Legionellen-Risiko - auf 60°C erhitzen',
    unusual_consumption: 'Ungewöhnlicher Energieverbrauch',
    maintenance_due: 'Wartung erforderlich',
    turn_on: 'Einschalten',
    turn_off: 'Ausschalten',
    control: 'Steuerung',
    // v1.6.0
    maintenance: 'Wartung',
    anode: 'Anode',
    cleaning: 'Reinigung',
    not_set: 'Nicht gesetzt',
    no_sensors: 'Keine Sensoren konfiguriert',
    remaining_days: 'Noch {days} Tage',
    overdue_days: 'Überfällig ({days} Tage)',
    status_heating: 'Heizt',
    status_ready: 'Bereit',
    status_cooling: 'Kühlt ab',
    hot_water: 'Warmwasser',
    showers: 'Duschen',
    stored_energy: 'Gespeicherte Energie',
    heat_loss: 'Wärmeverlust',
    time_to_cold: 'Kalt in',
    energy_today: 'Heute',
    history: 'Temperaturverlauf',
    show_history: 'Verlauf anzeigen',
    hide_history: 'Verlauf ausblenden',
    no_history: 'Noch keine Daten gesammelt',
    operation_mode: 'Modus',
    target_control: 'Zieltemperatur',
    electric_heating: 'Elektrische Heizung',
    solar_heating: 'Solarheizung',
    gas_heating: 'Gasheizung',
    heat_pump_heating: 'Wärmepumpe',
    mode_eco: 'Eco',
    mode_performance: 'Leistung',
    mode_high_demand: 'Hoher Bedarf',
    mode_heat_pump: 'Wärmepumpe',
    mode_electric: 'Elektrisch',
    mode_gas: 'Gas',
    mode_off: 'Aus',
    unavailable_entity: 'Entität nicht gefunden',
  },
  sk: {
    average_temp: 'Priemerná teplota',
    heating: 'Kúrenie',
    target: 'Cieľová teplota',
    anode_check: 'Kontrola anódy',
    cleaning_check: 'Čistenie',
    days_remaining: 'zostáva dní',
    overdue: 'po termíne',
    power_consumption: 'Spotreba',
    heating_source: 'Zdroj kúrenia',
    low_temperature: 'Nízka teplota!',
    temperature_drop: 'Prudký pokles teploty!',
    legionella_risk: 'Riziko legionely - ohrejte na 60°C',
    unusual_consumption: 'Neobvyklá spotreba energie',
    maintenance_due: 'Údržba je potrebná',
    turn_on: 'Zapnúť',
    turn_off: 'Vypnúť',
    control: 'Ovládanie',
    // v1.6.0
    maintenance: 'Údržba',
    anode: 'Anóda',
    cleaning: 'Čistenie',
    not_set: 'Nenastavené',
    no_sensors: 'Nie sú nakonfigurované žiadne senzory',
    remaining_days: 'Zostáva {days} dní',
    overdue_days: 'Po termíne ({days} dní)',
    status_heating: 'Ohrev',
    status_ready: 'Pripravené',
    status_cooling: 'Chladne',
    hot_water: 'Teplá voda',
    showers: 'spŕch',
    stored_energy: 'Uložená energia',
    heat_loss: 'Tepelná strata',
    time_to_cold: 'Vychladne za',
    energy_today: 'Dnes',
    history: 'História teplôt',
    show_history: 'Zobraziť históriu',
    hide_history: 'Skryť históriu',
    no_history: 'Zatiaľ nie sú nazbierané dáta',
    operation_mode: 'Režim',
    target_control: 'Cieľová teplota',
    electric_heating: 'Elektrický ohrev',
    solar_heating: 'Solárny ohrev',
    gas_heating: 'Plynový ohrev',
    heat_pump_heating: 'Tepelné čerpadlo',
    mode_eco: 'Eko',
    mode_performance: 'Výkon',
    mode_high_demand: 'Vysoká spotreba',
    mode_heat_pump: 'Tep. čerpadlo',
    mode_electric: 'Elektrina',
    mode_gas: 'Plyn',
    mode_off: 'Vypnuté',
    unavailable_entity: 'Entita nenájdená',
  },
  pl: {
    average_temp: 'Średnia temperatura',
    heating: 'Ogrzewanie',
    target: 'Temperatura docelowa',
    anode_check: 'Sprawdzenie anody',
    cleaning_check: 'Czyszczenie',
    days_remaining: 'dni pozostało',
    overdue: 'po terminie',
    power_consumption: 'Zużycie',
    heating_source: 'Źródło ogrzewania',
    low_temperature: 'Niska temperatura!',
    temperature_drop: 'Szybki spadek temperatury!',
    legionella_risk: 'Ryzyko legionelli - podgrzej do 60°C',
    unusual_consumption: 'Niezwykłe zużycie energii',
    maintenance_due: 'Wymagana konserwacja',
    turn_on: 'Włącz',
    turn_off: 'Wyłącz',
    control: 'Sterowanie',
    // v1.6.0
    maintenance: 'Konserwacja',
    anode: 'Anoda',
    cleaning: 'Czyszczenie',
    not_set: 'Nie ustawiono',
    no_sensors: 'Nie skonfigurowano czujników',
    remaining_days: 'Pozostało {days} dni',
    overdue_days: 'Po terminie ({days} dni)',
    status_heating: 'Grzanie',
    status_ready: 'Gotowe',
    status_cooling: 'Stygnie',
    hot_water: 'Ciepła woda',
    showers: 'pryszniców',
    stored_energy: 'Zmagazynowana energia',
    heat_loss: 'Straty ciepła',
    time_to_cold: 'Wystygnie za',
    energy_today: 'Dzisiaj',
    history: 'Historia temperatur',
    show_history: 'Pokaż historię',
    hide_history: 'Ukryj historię',
    no_history: 'Brak zebranych danych',
    operation_mode: 'Tryb',
    target_control: 'Temperatura docelowa',
    electric_heating: 'Ogrzewanie elektryczne',
    solar_heating: 'Ogrzewanie solarne',
    gas_heating: 'Ogrzewanie gazowe',
    heat_pump_heating: 'Pompa ciepła',
    mode_eco: 'Eko',
    mode_performance: 'Wydajność',
    mode_high_demand: 'Wysokie zapotrzebowanie',
    mode_heat_pump: 'Pompa ciepła',
    mode_electric: 'Elektryczny',
    mode_gas: 'Gaz',
    mode_off: 'Wyłączony',
    unavailable_entity: 'Nie znaleziono encji',
  },
};
